name: Laravel CI/CD with Docker

on:
  push:
    branches: [ main, test ]  # Trigger pada branch main atau dev
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'  # Sesuai versi PHP di Dockerfile
        extensions: mysql, mbstring, xml, gd, intl  # Ekstensi untuk Laravel/Filament

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Copy .env and generate key
      run: |
        cp .env.example .env
        php artisan key:generate --ansi

    - name: Run tests
      run: |
        php artisan test --coverage  # Jalankan PHPUnit tests untuk Laravel

    - name: Check coding standards
      run: composer run lint  # Opsional: Gunakan PHP CS Fixer atau Pint

  cd:
    needs: ci  # Jalankan CD hanya jika CI sukses
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Hanya deploy ke main branch
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-filament-app:latest  # Tag image

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Stop container lama
          cd ${{ secrets.SERVER_PATH }}
          docker-compose down
          
          # Pull image baru
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/laravel-filament-app:latest
          
          # Update docker-compose.yml jika perlu, lalu restart
          docker-compose up -d --build
          
          # Jalankan migrasi dan optimasi Laravel
          docker-compose exec app php artisan migrate --force
          docker-compose exec app php artisan config:cache
          docker-compose exec app php artisan route:cache
          docker-compose exec app php artisan view:cache
          
          # Set permission untuk Filament storage
          docker-compose exec app chmod -R 775 storage bootstrap/cache
